version: '3.8'

services:
  app:
    image: hjackson277/gt-radio
    env_file: .env

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
      - "8000:8000"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - /etc/letsencrypt/live/ebcert/fullchain:/etc/letsencrypt/live/ebcert/fullchain
    depends_on:
      - app
