branch-defaults:
  dev:
    environment: greattunes-app-dev
    group_suffix: null
  main:
    environment: greattunes-app-dev
global:
  application_name: greattunes-app
  branch: main
  default_ec2_keyname: null
  default_platform: Docker running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
